### ISSUE TITLE
exception when compiling resources

### ISSUE THREAD

**Issue by daniOlg** [revanced/revanced-manager#896]
### Type

Error at runtime

### Bug description

I'm patching 18.19.35 with default patch selection
Already tried reinstall and clear all data
Exception: brut.common.BrutException: could not exec (exit code = 1)

### Steps to reproduce

Step 1: Select APK from storage
Step 2: Patch with default selection

### Android version

12 with MIUI 14.0.1

### Manager version

1.3.0

### Target package name

com.google.android.youtube

### Target package version.

18.19.35

### Installation type

Non-root

### Patches selected.

Default selection

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied always-autorepeat
Applied client-spoof
Applied comments
Applied copy-video-url
Applied disable-auto-captions
Applied disable-fullscreen-panels
Applied disable-player-popup-panels
Applied disable-shorts-on-startup
Applied disable-zoom-haptics
Applied downloads
Applied enable-debugging
Applied hdr-auto-brightness
Applied hide-ads
Applied hide-album-cards
Applied hide-artist-card
Applied hide-autoplay-button
Applied hide-breaking-news-shelf
Applied hide-captions-button
Applied hide-cast-button
Applied hide-crowdfunding-box
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-filter-bar
Applied hide-floating-microphone-button
Applied hide-get-premium
Applied hide-info-cards
Applied hide-load-more-button
Applied hide-player-buttons
Applied hide-player-overlay
Applied hide-seekbar
Applied hide-shorts-components
Applied hide-timestamp
Applied hide-video-action-buttons
Applied hide-watch-in-vr
Applied hide-watermark
Applied minimized-playback
Applied navigation-buttons
Applied old-quality-layout
Applied open-links-externally
Applied remember-video-quality
Applied return-youtube-dislike
Applied seekbar-tapping
Applied sponsorblock
Applied spoof-app-version
Applied swipe-controls
Applied tablet-mini-player
Applied theme
Applied vanced-microg-support
Applied video-ads
Applied video-speed
Applied wide-searchbar
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~QxgrHIWvZaUY6kAX01wesw==/app.revanced.manager.flutter-6CJoVp55VQ5kxOQWxX73FA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6197226606902364359.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~QxgrHIWvZaUY6kAX01wesw==/app.revanced.manager.flutter-6CJoVp55VQ5kxOQWxX73FA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6197226606902364359.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KENQDO/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by kooooolaaa** [comment]
Same issue during the build via termux :(

**Comment by Ushie** [comment]
> Same issue during the build via termux :(

In that case, this is not a ReVanced Manager issue,

**Comment by Duvio** [comment]
> > Same issue during the build via termux :(
> 
> In that case, this is not a ReVanced Manager issue,

It's an aapt2/apktool issue. I suggest this to be mentioned to them too.

**Comment by Ushie** [comment]
The issue is technically resolved by https://github.com/revanced/revanced-patcher/pull/165 in our case

**Comment by Duvio** [comment]
> The issue is technically resolved by [revanced/revanced-patcher#165](https://github.com/revanced/revanced-patcher/pull/165) in our case

Can you give an ETA of when the next version will be released? The videos stopping and endlessly buffering after a minute and forcing me to use normal YouTube drives me insane.

**Comment by Ushie** [comment]
That issue has been resolved months back, include the `client-spoof` patch, if it doesn't function correctly then check in with the revanced-patches repo issues

**Comment by Duvio** [comment]
> That issue has been resolved months back, include the `client-spoof` patch, if it doesn't function correctly then check in with the revanced-patches repo issues

Thing is, i cannot patch YouTube because of the aapt2 issue we are currently commenting under

**Comment by yoshiask** [comment]
Why was this issue closed? I have the same problem, no patches can be applied because of this and the linked PR hasn't even been merged yet, let alone made its way into a release.

**Comment by Klusio19** [comment]
> Why was this issue closed? I have the same problem, no patches can be applied because of this and the linked PR hasn't even been merged yet, let alone made its way into a release.

Indeed. I still have the same problem, with the latest available Revanced Manager

**Comment by twwn** [comment]
Same problem with v1.8.0

**Comment by Andreu-G** [comment]
I am also having the same problem

**Comment by Kodehawa** [comment]
why is this closed? still an issue on 1.8.0, using a Samsung S22+ here.

**Comment by stephannn** [comment]
Hi everyone,
OnePlus 8 same issue ;)
